In [83]:
import numpy as np
import pandas as pd

In [84]:
df  = pd.read_csv(r"C:\Users\Abhinash\Desktop\SMSSpamCollection1.csv",
                  encoding='ISO-8859-1'
)
df.head()
#data=pd.read_csv(r"1653110050smsspamcollection1.csv",encoding='latin1')

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

#### Column renaming takes palce

In [85]:
df = df.rename(columns={"v1":"category",
                       "v2":"message"})
df.head()

category                                            message Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [86]:
df = df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1)
df.head()

category                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [87]:
# HAM -> 0 and SPAM ->1
df["Target"] = np.where(df["category"]=="ham",0,1)
df.head()

category                                            message  Target
0      ham  Go until jurong point, crazy.. Available only ...       0
1      ham                      Ok lar... Joking wif u oni...       0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...       1
3      ham  U dun say so early hor... U c already then say...       0
4      ham  Nah I don't think he goes to usf, he lives aro...       0

In [88]:
df.to_csv(r"C:\Users\Abhinash\Desktop\GUI-SPAM CLASSIFICATION\SPAMFILTER.csv")

### SPLIT DATA 

In [91]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df["message"],
                                                df["Target"],
                                                test_size=0.25,
                                                random_state =42)

In [92]:
print("Original data size: ", df.shape)
print("Original data size: ", x_train.shape)
print("Original data size: ", x_test.shape)

Original data size:  (5572, 3)
Original data size:  (4179,)
Original data size:  (1393,)


In [93]:
from sklearn.feature_extraction.text import CountVectorizer

In [94]:
cv = CountVectorizer()

In [95]:
train = cv.fit_transform(x_train)
test = cv.transform(x_test)

In [96]:
train

<4179x7441 sparse matrix of type '<class 'numpy.int64'>'
	with 55194 stored elements in Compressed Sparse Row format>

In [97]:
test

<1393x7441 sparse matrix of type '<class 'numpy.int64'>'
	with 17365 stored elements in Compressed Sparse Row format>

In [98]:
from sklearn.naive_bayes import MultinomialNB

In [99]:
NB = MultinomialNB()

In [100]:
NB.fit(train,y_train)

MultinomialNB()

In [101]:
pred = NB.predict(test)
pred

array([0, 0, 1, ..., 0, 0, 0])

In [102]:
Y_test = np.array([i for i in y_test])
Y_test

array([0, 0, 1, ..., 0, 0, 0])

In [103]:
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,pred))

[[1199    3]
 [  22  169]]


In [104]:
print("accuracy of model is:",accuracy_score(Y_test,pred))

accuracy of model is: 0.9820531227566404


In [105]:
#spam classification: what you will look to evalute model
# recall | Precision

In [106]:
# suppose ypu model classify a ham as spam that is ok 
# model should not classify a spam as ham this is not allowed
# Precision score we need to look

In [107]:
from sklearn.metrics import precision_score

In [108]:
print("Precision score is:", precision_score(Y_test,pred))

Precision score is: 0.9825581395348837


In [109]:
df.head()

category                                            message  Target
0      ham  Go until jurong point, crazy.. Available only ...       0
1      ham                      Ok lar... Joking wif u oni...       0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...       1
3      ham  U dun say so early hor... U c already then say...       0
4      ham  Nah I don't think he goes to usf, he lives aro...       0

In [130]:
df["message"].head()[2]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [111]:
# lets test this for a single message
ms = str(input("Enter Text Message :"))
test1 = cv.transform([ms,])
test1

Enter Text Message :Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...


<1x7441 sparse matrix of type '<class 'numpy.int64'>'
	with 18 stored elements in Compressed Sparse Row format>

In [112]:
arr = test1.toarray()
arr
arr.shape

(1, 7441)

In [113]:
pred1 = NB.predict(test1)
pred1

array([0])

In [114]:
pred1[0]

0

In [115]:
ref = {0:"HAM",1:"SPAM"}
ref[pred1[0]]

'HAM'

### CREATE A PICKLE OR JSON FORMAT FOR MY MODEL

In [117]:
import json, pickle
from sklearn.naive_bayes import MultinomialNB
NB = MultinomialNB()
NB.fit(train,y_train)

MultinomialNB()

In [118]:
file_name = r"C:\Users\Abhinash\Desktop\GUI-SPAM CLASSIFICATION\model5.pickle"
pickle.dump(NB, open(file_name, "wb"))

In [68]:
MD = pickle.dumps(NB)
f = open(r"C:\Users\Abhinash\Desktop\GUI-SPAM CLASSIFICATION\model2.pickle","wb")
f.write(MD)
f.close()

In [ ]:
# MODEL OVER CODE

In [124]:
import numpy as np
import pandas as pd


MultinomialNB()

In [133]:
# creating a normal GUI WINDOW
from tkinter import *
import tkinter
import pandas as pd
import numpy as np
import pickle
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

window = Tk()
# this chunck set the size of pixel for GUI
window.geometry("600x400")

# change the title for Window
window.title("TEXT CLASSIFIER")

# change GUI background color
window.configure(background= "azure")

# lets add a label to our GUI
Label(window,text ="EMAIL CLASSIFIER APPLICATION",
     font = 15,
     bg = "azure",
     fg = "red",
     relief = "solid",
     width = 40).place(x=120,y=50)

Label(window,text ="EMAIL MESSAGE",
     font = 10,
     bg = "azure",
     fg = "black",
     relief = "solid",
     width = 20).place(x=80,y=150)


Label(window,text ="MESSAGE CATEOGRY",
     font = 10,
     bg = "azure",
     fg = "black",
     relief = "solid",
     width = 20).place(x=80,y=200)


message = StringVar()
# Entry Widget
Entry(window, textvariable =  message).place(x = 300 , y = 150)


def PREDICT():
    df = pd.read_csv(r"C:\Users\Abhinash\Desktop\GUI-SPAM CLASSIFICATION\SPAMFILTER.csv")
    x_train,x_test,y_train,y_test = train_test_split(df["message"],
                                                df["Target"],
                                                test_size=0.25,
                                                random_state =42)
  
    cv = CountVectorizer()
    cv.fit_transform(x_train)
    # line is to load a already trained model
    file_name = r"C:\Users\Abhinash\Desktop\GUI-SPAM CLASSIFICATION\model5.pickle"
    MOD = pickle.load(open(file_name, "rb"))
    
    # the message form GUI come to beckend
    mes = message.get()
    
    # we will create model and then feed the data to model and model will clasify the following instance
    test = cv.transform([mes,])
    pred  = MOD.predict(test)
    pred = pred[0]
    ref = {0:"HAM",1:"SPAM"}
    ans = ref[pred]
    # ans-> 0/1
    Label(window, text = " "*30,
         width = 20,
         bg ="white",
         fg="black",
         relief = "sunken").place(x = 300,y=200)
    if ans == "HAM":
        Label(window, text = ans,
              width = 20,
              bg ="white",
              fg="green",
              relief = "sunken").place(x = 300,y=200)
    else:
        Label(window, text = ans,
              width = 20,
              bg ="white",
              fg="red",
              relief = "sunken").place(x = 300,y=200)
    


Button(window, text ="PREDICT",
      width = 20,
      bg = "light green",
      fg = "black",
      command = PREDICT).place(x = 120, y = 290)



def EXIT_GUI():
    window.destroy()

Button(window, text ="Exit GUI",
      width = 20,
      bg = "light green",
      fg = "red",
      command = EXIT_GUI ).place(x = 300, y = 290)


window.resizable(0,0)
# this line of code will be always at last
window.mainloop()

In [136]:
index = [2,5,6]
val = [1,1,1]
total = [0,1,2,3,4,5,6,7,8,9]
arr = [0 for i in range(0,10)]
arr

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [138]:
for j in index:
    arr[j]=1
print(arr)

[0, 0, 1, 0, 0, 1, 1, 0, 0, 0]
